Setting:
  Name: Worklyzer
  Travel: 2 # 每隔 n 个小时，遍历所有的仓库更新至状态
Web:
  Host: 127.0.0.1 # 监听地址
  Port: 8080 # 监听端口
Database:
  Engine: sqlite3 # 所使用的数据库引擎 sqlite3 mysql postgresql
  Path: ./work.db # 如果数据库引擎使用的是 sqlite3 指定数据库所在路径
  Host: 127.0.0.1 # 数据库的地址
  Username: tosone # 数据库的用户名
  Password: 8541539655 # 数据库的密码
  Port: 3306 # 数据库的端口
Log:
  App: app.log # 程序运行过程中产生的日志路径
  ShowSQL: true # 是否产生数据库日志
  Database: db.log # 数据库交互产生的日志路径
  Level: 0 # 日志等级
  MaxAge: 30 # 日志最长的保留日期
  MaxSize: 10 # 每个日志最大的体积（单位 Mb）
  MaxBackups: 3 # 最多备份的日志数量
  LocalTime: true # 是否使用当前系统时间
  Compress: true # 日志是否启用压缩
UserMgr:
  - Name: tosone
    ApiKey: bbc0b1e9-5e9e-4e26-9218-b917afa26998